-- ARCHIVO GENERADO. No editar a mano: se regenera con `pnpm seed:generar`.
-- Fuente: data/crosssell_rules.json y data/procesos.json.
--
-- Todo va con ON CONFLICT DO NOTHING: el seed llena lo que falta y nunca pisa lo que
-- Oficina Tecnica edito. Para re-sincronizar una regla hay que borrar la fila primero.

begin;

-- 9 lineas de producto.
insert into dominio (codigo, nombre, orden) values
  ('tuberia', 'Tubería de proceso industrial', 1),
  ('sanitario', 'Línea sanitaria / alimenticia', 2),
  ('materiaprima', 'Materia prima', 3),
  ('tapas', 'Tapas y puertas de tanque', 4),
  ('bulones', 'Bulonería y fijación', 5),
  ('arquitectura', 'Línea arquitectura', 6),
  ('soldadura', 'Consumibles de soldadura', 7),
  ('abrasivos', 'Abrasivos y acabado', 8),
  ('quimica', 'Auxiliares y química', 9)
on conflict (codigo) do nothing;

-- 69 categorias funcionales.
insert into categoria (codigo, etiqueta) values
  ('cano', 'Caños / tubos'),
  ('tubo', 'Tubos'),
  ('acc_soldar_ind', 'Accesorios para soldar (industriales)'),
  ('acc_soldar_san', 'Accesorios sanitarios para soldar'),
  ('brida', 'Bridas'),
  ('niple', 'Niples'),
  ('acc_rosc_sw', 'Accesorios roscados / socket weld'),
  ('valvula_ind', 'Válvulas industriales'),
  ('valvula_san', 'Válvulas sanitarias'),
  ('acc_valvula_san', 'Repuestos de válvula sanitaria'),
  ('actuador', 'Actuadores'),
  ('union_sanitaria', 'Uniones sanitarias'),
  ('bomba', 'Bombas'),
  ('acc_bomba', 'Repuestos de bomba'),
  ('instrumentacion', 'Instrumentación'),
  ('acc_tanque', 'Accesorios de tanque'),
  ('sistema_limpieza', 'Sistema de limpieza (spray ball)'),
  ('tapa_puerta', 'Tapas y puertas'),
  ('acc_tapa', 'Herrajes de tapa'),
  ('mirilla', 'Mirillas'),
  ('soporte_san', 'Soportes sanitarios'),
  ('filtro_san', 'Filtros sanitarios'),
  ('filtro_ind', 'Filtros industriales'),
  ('acople_rapido', 'Acoples rápidos'),
  ('junta', 'Juntas / gaskets'),
  ('chapa', 'Chapas / bobinas'),
  ('barra', 'Barras'),
  ('planchuela', 'Planchuelas'),
  ('angulo', 'Ángulos'),
  ('otra_mp', 'Otras materias primas'),
  ('bulon', 'Tornillos / bulones'),
  ('tuerca', 'Tuercas'),
  ('arandela', 'Arandelas'),
  ('varilla_roscada', 'Varillas roscadas / espárragos'),
  ('abrazadera', 'Abrazaderas'),
  ('remache', 'Remaches'),
  ('cable', 'Cables'),
  ('baranda', 'Barandas / pasamanos'),
  ('griferia', 'Grifería'),
  ('acc_vidrio', 'Accesorios para vidrio'),
  ('herraje_arq', 'Herrajes de arquitectura'),
  ('acc_bano', 'Accesorios de baño'),
  ('arq_otro', 'Otros de arquitectura'),
  ('broca', 'Brocas'),
  ('varilla_tig', 'Varilla TIG'),
  ('alambre_mig', 'Alambre MIG'),
  ('electrodo_revestido', 'Electrodo revestido'),
  ('tungsteno', 'Electrodo de tungsteno'),
  ('combo', 'Combos de consumibles'),
  ('disco_corte', 'Discos de corte'),
  ('flap', 'Discos flap'),
  ('lija', 'Lijas'),
  ('acabado', 'Vellón / acabado'),
  ('cepillo', 'Cepillos / cardas'),
  ('pulido', 'Pasta de pulido'),
  ('banda', 'Bandas'),
  ('fresa', 'Fresas'),
  ('decapante', 'Decapante'),
  ('pasivante', 'Pasivante'),
  ('neutralizante', 'Neutralizante'),
  ('limpieza', 'Limpiadores'),
  ('revestimiento', 'Revestimiento protector'),
  ('respaldo', 'Respaldo de raíz (pasta cerámica)'),
  ('antiproyecciones', 'Antiproyecciones'),
  ('detector', 'Detector ferrita/molibdeno'),
  ('ndt', 'Tinta penetrante (END)'),
  ('sellador_rosca', 'Sellador / fijador / antigripante de rosca'),
  ('adhesivo_montaje', 'Adhesivos / selladores de montaje'),
  ('lubricante', 'Lubricantes')
on conflict (codigo) do nothing;

-- La categoria de descarte del clasificador. Inactiva: nunca se sugiere, pero tiene que
-- existir porque catalogo_item.categoria_codigo tiene FK contra categoria.codigo.
insert into categoria (codigo, etiqueta, activo)
values ('otro', 'Sin clasificar', false)
on conflict (codigo) do nothing;

-- 27 disparadores de venta cruzada.
insert into tipo_producto (codigo, dominio_id, nombre, pregunta_grado, orden)
select v.codigo, d.id, v.nombre, v.pregunta_grado, v.orden
from (values
  ('cano', 'tuberia', 'Caño / tubo de proceso', true, 1),
  ('acc_soldar_ind', 'tuberia', 'Accesorio para soldar (codo/tee/reducción)', true, 2),
  ('brida', 'tuberia', 'Brida', false, 3),
  ('niple', 'tuberia', 'Niple / medio niple', false, 4),
  ('acc_rosc_sw', 'tuberia', 'Accesorio roscado / socket weld', false, 5),
  ('valvula_ind', 'tuberia', 'Válvula industrial', false, 6),
  ('union_sanitaria', 'sanitario', 'Unión sanitaria (Clamp/SMS/DIN)', false, 7),
  ('acc_soldar_san', 'sanitario', 'Accesorio sanitario para soldar (incl. pharma)', true, 8),
  ('valvula_san', 'sanitario', 'Válvula sanitaria (mariposa/pistón)', false, 9),
  ('bomba', 'sanitario', 'Bomba sanitaria / centrífuga', false, 10),
  ('instrumentacion', 'sanitario', 'Instrumentación / alta presión', false, 11),
  ('acc_tanque', 'sanitario', 'Accesorio para tanque', false, 12),
  ('chapa', 'materiaprima', 'Chapa / bobina', true, 13),
  ('barra', 'materiaprima', 'Barra redonda', true, 14),
  ('planchuela', 'materiaprima', 'Planchuela', true, 15),
  ('angulo', 'materiaprima', 'Ángulo', true, 16),
  ('tapa_puerta', 'tapas', 'Tapa / puerta de tanque', false, 17),
  ('bulon', 'bulones', 'Tornillo / bulón', false, 18),
  ('varilla_roscada', 'bulones', 'Varilla roscada / espárrago', false, 19),
  ('baranda', 'arquitectura', 'Baranda / pasamanos', false, 20),
  ('griferia', 'arquitectura', 'Grifería / herrajes de baño', false, 21),
  ('tungsteno', 'soldadura', 'Electrodo de tungsteno', false, 22),
  ('varilla_tig', 'soldadura', 'Varilla TIG', false, 23),
  ('alambre_mig', 'soldadura', 'Alambre MIG', false, 24),
  ('electrodo_revestido', 'soldadura', 'Electrodo revestido (MMA)', false, 25),
  ('disco_corte', 'abrasivos', 'Disco de corte / abrasivo', false, 26),
  ('decapante', 'quimica', 'Decapante / pasivante', false, 27)
) as v(codigo, dominio, nombre, pregunta_grado, orden)
join dominio d on d.codigo = v.dominio
on conflict (codigo) do nothing;

-- 100 complementos: la regla de venta cruzada propiamente dicha.
insert into complemento (tipo_producto_id, nombre, prioridad, motivo, depende_del_grado, orden)
select tp.id, v.nombre, v.prioridad::prioridad_complemento, v.motivo, v.depende_del_grado, v.orden
from (values
  ('cano', 'Accesorios para soldar', 'oblig', 'Codos, tees y reducciones del mismo grado para armar la línea.', false, 1),
  ('cano', 'Consumible de aporte', 'oblig', 'Para unir los tramos; el grado de aporte lo define el grado del caño.', true, 2),
  ('cano', 'Bridas', 'reco', 'Conexiones desmontables a equipos y válvulas.', false, 3),
  ('cano', 'Química de terminación', 'oblig', 'Decapar y pasivar cada soldadura para que la junta no oxide.', false, 4),
  ('cano', 'Abrasivos', 'reco', 'Corte, biselado y acabado del cordón.', false, 5),
  ('acc_soldar_ind', 'Caño / tubo', 'reco', 'El tramo recto que conecta los accesorios.', false, 1),
  ('acc_soldar_ind', 'Consumible de aporte', 'oblig', 'Aporte del grado del accesorio.', true, 2),
  ('acc_soldar_ind', 'Bridas', 'reco', 'Conexión desmontable de la línea.', false, 3),
  ('acc_soldar_ind', 'Química de terminación', 'oblig', 'Decapar y pasivar cada soldadura.', false, 4),
  ('acc_soldar_ind', 'Abrasivos', 'reco', 'Preparación y acabado.', false, 5),
  ('brida', 'Juntas / gaskets', 'oblig', 'Toda brida sella contra una junta; material según fluido y temperatura.', false, 1),
  ('brida', 'Espárragos, tuercas y arandelas', 'oblig', 'El set de apriete de la brida.', false, 2),
  ('brida', 'Consumible de aporte', 'reco', 'Si es welding-neck o slip-on hay que soldarla al caño.', true, 3),
  ('brida', 'Caño', 'reco', 'El tramo que se une a la brida.', false, 4),
  ('niple', 'Accesorios roscados / SW', 'oblig', 'El niple conecta los fittings roscados.', false, 1),
  ('niple', 'Sellador / antigripante de rosca', 'oblig', 'Sellar y proteger la unión roscada.', false, 2),
  ('niple', 'Válvulas', 'reco', 'Cierre o regulación en la línea roscada.', false, 3),
  ('acc_rosc_sw', 'Niples', 'reco', 'Conectores entre fittings.', false, 1),
  ('acc_rosc_sw', 'Sellador / antigripante de rosca', 'oblig', 'Sellado de la unión roscada.', false, 2),
  ('acc_rosc_sw', 'Válvulas', 'reco', '', false, 3),
  ('acc_rosc_sw', 'Consumible (versiones SW)', 'reco', 'Las versiones socket-weld se sueldan.', false, 4),
  ('valvula_ind', 'Bridas', 'reco', 'Para montar la válvula bridada.', false, 1),
  ('valvula_ind', 'Juntas', 'oblig', 'Sellado de las caras de montaje.', false, 2),
  ('valvula_ind', 'Espárragos y tuercas', 'oblig', 'Set de apriete.', false, 3),
  ('valvula_ind', 'Accesorios roscados / niples', 'reco', 'Si es válvula roscada.', false, 4),
  ('union_sanitaria', 'Juntas sanitarias', 'oblig', 'La unión clamp no sella sin junta: EPDM/silicona/PTFE/Viton según fluido y temperatura.', false, 1),
  ('union_sanitaria', 'Abrazaderas clamp', 'oblig', 'El collar que cierra la unión.', false, 2),
  ('union_sanitaria', 'Accesorios sanitarios para soldar', 'reco', 'Para empalmar la unión a la línea.', false, 3),
  ('union_sanitaria', 'Tubo sanitario', 'reco', '', false, 4),
  ('acc_soldar_san', 'Consumible de aporte 316L', 'oblig', 'Aporte bajo carbono (316L/308L) para no perder corrosión ni contaminar producto.', true, 1),
  ('acc_soldar_san', 'Respaldo / back-purge', 'oblig', 'Proteger la raíz interior (cara en contacto con producto).', false, 2),
  ('acc_soldar_san', 'Química: decapar/pasivar + revestimiento', 'oblig', 'Terminación higiénica de la soldadura interior.', false, 3),
  ('acc_soldar_san', 'Uniones sanitarias', 'reco', '', false, 4),
  ('valvula_san', 'Juntas y kit de repuesto', 'oblig', 'Sellos EPDM/silicona/Viton: repuesto de desgaste.', false, 1),
  ('valvula_san', 'Actuadores', 'reco', 'Para automatizar (mariposa neumática).', false, 2),
  ('valvula_san', 'Uniones sanitarias', 'reco', 'Para montar la válvula a la línea.', false, 3),
  ('valvula_san', 'Instrumentación', 'opc', '', false, 4),
  ('bomba', 'Repuestos de bomba', 'oblig', 'Sellos mecánicos, rodetes y repuestos de desgaste.', false, 1),
  ('bomba', 'Uniones sanitarias', 'oblig', 'Para conectar la bomba a la línea.', false, 2),
  ('bomba', 'Válvulas', 'reco', '', false, 3),
  ('bomba', 'Instrumentación', 'opc', 'Manómetros, sensores.', false, 4),
  ('instrumentacion', 'Conectores y adaptadores', 'oblig', 'Para completar el armado del instrumento.', false, 1),
  ('instrumentacion', 'Válvulas y manifolds', 'reco', '', false, 2),
  ('instrumentacion', 'Juntas', 'reco', '', false, 3),
  ('acc_tanque', 'Juntas', 'oblig', 'Sellado de bocas y conexiones.', false, 1),
  ('acc_tanque', 'Tapas y puertas', 'reco', '', false, 2),
  ('acc_tanque', 'Sistema de limpieza (spray ball)', 'reco', 'CIP del tanque.', false, 3),
  ('acc_tanque', 'Mirillas y soportes', 'opc', '', false, 4),
  ('chapa', 'Abrasivos: corte y acabado', 'oblig', 'Para cortar, biselar y dar la terminación pedida.', false, 1),
  ('chapa', 'Química de terminación', 'oblig', 'Decapar/pasivar zonas trabajadas; limpiador de inox.', false, 2),
  ('chapa', 'Consumible de aporte', 'reco', 'Si se va a soldar la chapa.', true, 3),
  ('chapa', 'Película / revestimiento protector', 'reco', 'Proteger la cara durante manipuleo.', false, 4),
  ('chapa', 'Brocas', 'opc', 'Si se perfora.', false, 5),
  ('barra', 'Brocas', 'reco', 'Mecanizado y perforado.', false, 1),
  ('barra', 'Abrasivos', 'reco', 'Acabado y pulido.', false, 2),
  ('barra', 'Consumible de aporte', 'opc', 'Si se suelda.', true, 3),
  ('planchuela', 'Abrasivos', 'reco', 'Corte y acabado.', false, 1),
  ('planchuela', 'Consumible de aporte', 'opc', '', true, 2),
  ('planchuela', 'Brocas', 'opc', '', false, 3),
  ('angulo', 'Abrasivos', 'reco', 'Corte y acabado.', false, 1),
  ('angulo', 'Consumible de aporte', 'opc', '', true, 2),
  ('tapa_puerta', 'Juntas de tapa', 'oblig', 'La tapa sella contra su junta: repuesto de desgaste habitual.', false, 1),
  ('tapa_puerta', 'Herrajes (bisagras, manijas, cierres)', 'oblig', 'Accesorios de la tapa.', false, 2),
  ('tapa_puerta', 'Bulonería', 'reco', 'Fijación de la tapa.', false, 3),
  ('tapa_puerta', 'Accesorios de tanque', 'opc', '', false, 4),
  ('bulon', 'Tuercas', 'oblig', 'Todo bulón necesita su tuerca del mismo paso.', false, 1),
  ('bulon', 'Arandelas', 'reco', 'Plana y de presión para distribuir la carga.', false, 2),
  ('bulon', 'Antigripante / pasta lubricante', 'oblig', 'En inox el galling es crítico: la rosca se agarrota en seco. La pasta lo evita.', false, 3),
  ('bulon', 'Fijador de rosca', 'reco', 'Evita aflojamiento por vibración.', false, 4),
  ('varilla_roscada', 'Tuercas', 'oblig', '', false, 1),
  ('varilla_roscada', 'Arandelas', 'reco', '', false, 2),
  ('varilla_roscada', 'Antigripante', 'oblig', 'Evitar agarrotamiento de la rosca inox.', false, 3),
  ('baranda', 'Herrajes y conectores', 'oblig', 'Curvas, uniones, soportes de pared.', false, 1),
  ('baranda', 'Accesorios para vidrio', 'reco', 'Si lleva paños de vidrio.', false, 2),
  ('baranda', 'Adhesivo / sellador de montaje', 'oblig', 'Loctite 680 para uniones tubo-conector + sellador.', false, 3),
  ('baranda', 'Abrasivos de acabado', 'reco', 'Satinado o pulido del pasamanos.', false, 4),
  ('baranda', 'Limpiador / pulidor', 'reco', '', false, 5),
  ('griferia', 'Accesorios y repuestos', 'reco', '', false, 1),
  ('griferia', 'Selladores / fijadores', 'reco', '', false, 2),
  ('griferia', 'Limpiador', 'opc', '', false, 3),
  ('tungsteno', 'Varilla TIG de aporte', 'oblig', 'Quien compra tungsteno suelda TIG: necesita la varilla.', false, 1),
  ('tungsteno', 'Respaldo de raíz', 'reco', 'Pasta cerámica para proteger la raíz.', false, 2),
  ('tungsteno', 'Química de terminación', 'oblig', 'Decapar y pasivar el cordón.', false, 3),
  ('tungsteno', 'Acabado', 'reco', '', false, 4),
  ('varilla_tig', 'Electrodo de tungsteno', 'oblig', 'La varilla no enciende sola; el tungsteno según espesor.', false, 1),
  ('varilla_tig', 'Respaldo de raíz', 'reco', '', false, 2),
  ('varilla_tig', 'Química de terminación', 'oblig', '', false, 3),
  ('varilla_tig', 'Abrasivos', 'reco', '', false, 4),
  ('alambre_mig', 'Antiproyecciones', 'oblig', 'El MIG salpica; evita pegado de salpicaduras y reproceso.', false, 1),
  ('alambre_mig', 'Química de terminación', 'oblig', '', false, 2),
  ('alambre_mig', 'Abrasivos', 'reco', '', false, 3),
  ('electrodo_revestido', 'Antiproyecciones', 'oblig', '', false, 1),
  ('electrodo_revestido', 'Abrasivos', 'oblig', 'Remoción de escoria y acabado.', false, 2),
  ('electrodo_revestido', 'Química de terminación', 'oblig', '', false, 3),
  ('disco_corte', 'Acabado progresivo', 'reco', 'Bajar grano con flap, lija y vellón.', false, 1),
  ('disco_corte', 'Cepillo de inox', 'reco', 'Carda de acero inox (nunca de carbono, contamina).', false, 2),
  ('disco_corte', 'Decapado y pasivado', 'oblig', 'Amolar inox altera la capa pasiva: decapar y pasivar.', false, 3),
  ('decapante', 'Secuencia: pasivar y neutralizar', 'oblig', 'Decapar→pasivar→neutralizar es una sola secuencia.', false, 1),
  ('decapante', 'Limpiadores y protección', 'reco', '', false, 2),
  ('decapante', 'Verificación', 'opc', 'Detector de ferrita/molibdeno.', false, 3)
) as v(tipo, nombre, prioridad, motivo, depende_del_grado, orden)
join tipo_producto tp on tp.codigo = v.tipo
on conflict (tipo_producto_id, nombre) do nothing;

-- 172 familias asociadas a los complementos.
insert into complemento_categoria (complemento_id, categoria_id, orden)
select c.id, cat.id, v.orden
from (values
  ('cano', 'Accesorios para soldar', 'acc_soldar_ind', 1),
  ('cano', 'Consumible de aporte', 'varilla_tig', 1),
  ('cano', 'Consumible de aporte', 'alambre_mig', 2),
  ('cano', 'Consumible de aporte', 'electrodo_revestido', 3),
  ('cano', 'Bridas', 'brida', 1),
  ('cano', 'Química de terminación', 'decapante', 1),
  ('cano', 'Química de terminación', 'pasivante', 2),
  ('cano', 'Química de terminación', 'neutralizante', 3),
  ('cano', 'Abrasivos', 'disco_corte', 1),
  ('cano', 'Abrasivos', 'flap', 2),
  ('cano', 'Abrasivos', 'lija', 3),
  ('acc_soldar_ind', 'Caño / tubo', 'cano', 1),
  ('acc_soldar_ind', 'Caño / tubo', 'tubo', 2),
  ('acc_soldar_ind', 'Consumible de aporte', 'varilla_tig', 1),
  ('acc_soldar_ind', 'Consumible de aporte', 'alambre_mig', 2),
  ('acc_soldar_ind', 'Consumible de aporte', 'electrodo_revestido', 3),
  ('acc_soldar_ind', 'Bridas', 'brida', 1),
  ('acc_soldar_ind', 'Química de terminación', 'decapante', 1),
  ('acc_soldar_ind', 'Química de terminación', 'pasivante', 2),
  ('acc_soldar_ind', 'Química de terminación', 'neutralizante', 3),
  ('acc_soldar_ind', 'Abrasivos', 'disco_corte', 1),
  ('acc_soldar_ind', 'Abrasivos', 'flap', 2),
  ('acc_soldar_ind', 'Abrasivos', 'lija', 3),
  ('brida', 'Juntas / gaskets', 'junta', 1),
  ('brida', 'Espárragos, tuercas y arandelas', 'varilla_roscada', 1),
  ('brida', 'Espárragos, tuercas y arandelas', 'tuerca', 2),
  ('brida', 'Espárragos, tuercas y arandelas', 'arandela', 3),
  ('brida', 'Consumible de aporte', 'varilla_tig', 1),
  ('brida', 'Consumible de aporte', 'alambre_mig', 2),
  ('brida', 'Consumible de aporte', 'electrodo_revestido', 3),
  ('brida', 'Caño', 'cano', 1),
  ('niple', 'Accesorios roscados / SW', 'acc_rosc_sw', 1),
  ('niple', 'Sellador / antigripante de rosca', 'sellador_rosca', 1),
  ('niple', 'Sellador / antigripante de rosca', 'lubricante', 2),
  ('niple', 'Válvulas', 'valvula_ind', 1),
  ('acc_rosc_sw', 'Niples', 'niple', 1),
  ('acc_rosc_sw', 'Sellador / antigripante de rosca', 'sellador_rosca', 1),
  ('acc_rosc_sw', 'Sellador / antigripante de rosca', 'lubricante', 2),
  ('acc_rosc_sw', 'Válvulas', 'valvula_ind', 1),
  ('acc_rosc_sw', 'Consumible (versiones SW)', 'electrodo_revestido', 1),
  ('acc_rosc_sw', 'Consumible (versiones SW)', 'varilla_tig', 2),
  ('valvula_ind', 'Bridas', 'brida', 1),
  ('valvula_ind', 'Juntas', 'junta', 1),
  ('valvula_ind', 'Espárragos y tuercas', 'varilla_roscada', 1),
  ('valvula_ind', 'Espárragos y tuercas', 'tuerca', 2),
  ('valvula_ind', 'Espárragos y tuercas', 'arandela', 3),
  ('valvula_ind', 'Accesorios roscados / niples', 'acc_rosc_sw', 1),
  ('valvula_ind', 'Accesorios roscados / niples', 'niple', 2),
  ('union_sanitaria', 'Juntas sanitarias', 'junta', 1),
  ('union_sanitaria', 'Abrazaderas clamp', 'abrazadera', 1),
  ('union_sanitaria', 'Accesorios sanitarios para soldar', 'acc_soldar_san', 1),
  ('union_sanitaria', 'Tubo sanitario', 'tubo', 1),
  ('acc_soldar_san', 'Consumible de aporte 316L', 'varilla_tig', 1),
  ('acc_soldar_san', 'Consumible de aporte 316L', 'alambre_mig', 2),
  ('acc_soldar_san', 'Respaldo / back-purge', 'respaldo', 1),
  ('acc_soldar_san', 'Química: decapar/pasivar + revestimiento', 'decapante', 1),
  ('acc_soldar_san', 'Química: decapar/pasivar + revestimiento', 'pasivante', 2),
  ('acc_soldar_san', 'Química: decapar/pasivar + revestimiento', 'revestimiento', 3),
  ('acc_soldar_san', 'Uniones sanitarias', 'union_sanitaria', 1),
  ('valvula_san', 'Juntas y kit de repuesto', 'junta', 1),
  ('valvula_san', 'Juntas y kit de repuesto', 'acc_valvula_san', 2),
  ('valvula_san', 'Actuadores', 'actuador', 1),
  ('valvula_san', 'Uniones sanitarias', 'union_sanitaria', 1),
  ('valvula_san', 'Instrumentación', 'instrumentacion', 1),
  ('bomba', 'Repuestos de bomba', 'acc_bomba', 1),
  ('bomba', 'Uniones sanitarias', 'union_sanitaria', 1),
  ('bomba', 'Válvulas', 'valvula_san', 1),
  ('bomba', 'Instrumentación', 'instrumentacion', 1),
  ('instrumentacion', 'Conectores y adaptadores', 'instrumentacion', 1),
  ('instrumentacion', 'Válvulas y manifolds', 'valvula_ind', 1),
  ('instrumentacion', 'Juntas', 'junta', 1),
  ('acc_tanque', 'Juntas', 'junta', 1),
  ('acc_tanque', 'Tapas y puertas', 'tapa_puerta', 1),
  ('acc_tanque', 'Sistema de limpieza (spray ball)', 'sistema_limpieza', 1),
  ('acc_tanque', 'Mirillas y soportes', 'mirilla', 1),
  ('acc_tanque', 'Mirillas y soportes', 'soporte_san', 2),
  ('chapa', 'Abrasivos: corte y acabado', 'disco_corte', 1),
  ('chapa', 'Abrasivos: corte y acabado', 'flap', 2),
  ('chapa', 'Abrasivos: corte y acabado', 'lija', 3),
  ('chapa', 'Abrasivos: corte y acabado', 'acabado', 4),
  ('chapa', 'Química de terminación', 'decapante', 1),
  ('chapa', 'Química de terminación', 'pasivante', 2),
  ('chapa', 'Química de terminación', 'limpieza', 3),
  ('chapa', 'Consumible de aporte', 'varilla_tig', 1),
  ('chapa', 'Consumible de aporte', 'alambre_mig', 2),
  ('chapa', 'Consumible de aporte', 'electrodo_revestido', 3),
  ('chapa', 'Película / revestimiento protector', 'revestimiento', 1),
  ('chapa', 'Brocas', 'broca', 1),
  ('barra', 'Brocas', 'broca', 1),
  ('barra', 'Abrasivos', 'flap', 1),
  ('barra', 'Abrasivos', 'lija', 2),
  ('barra', 'Abrasivos', 'pulido', 3),
  ('barra', 'Consumible de aporte', 'varilla_tig', 1),
  ('barra', 'Consumible de aporte', 'electrodo_revestido', 2),
  ('planchuela', 'Abrasivos', 'flap', 1),
  ('planchuela', 'Abrasivos', 'lija', 2),
  ('planchuela', 'Abrasivos', 'disco_corte', 3),
  ('planchuela', 'Consumible de aporte', 'varilla_tig', 1),
  ('planchuela', 'Consumible de aporte', 'electrodo_revestido', 2),
  ('planchuela', 'Brocas', 'broca', 1),
  ('angulo', 'Abrasivos', 'flap', 1),
  ('angulo', 'Abrasivos', 'disco_corte', 2),
  ('angulo', 'Consumible de aporte', 'varilla_tig', 1),
  ('angulo', 'Consumible de aporte', 'electrodo_revestido', 2),
  ('tapa_puerta', 'Juntas de tapa', 'junta', 1),
  ('tapa_puerta', 'Herrajes (bisagras, manijas, cierres)', 'acc_tapa', 1),
  ('tapa_puerta', 'Bulonería', 'bulon', 1),
  ('tapa_puerta', 'Bulonería', 'tuerca', 2),
  ('tapa_puerta', 'Accesorios de tanque', 'acc_tanque', 1),
  ('bulon', 'Tuercas', 'tuerca', 1),
  ('bulon', 'Arandelas', 'arandela', 1),
  ('bulon', 'Antigripante / pasta lubricante', 'sellador_rosca', 1),
  ('bulon', 'Antigripante / pasta lubricante', 'lubricante', 2),
  ('bulon', 'Fijador de rosca', 'sellador_rosca', 1),
  ('varilla_roscada', 'Tuercas', 'tuerca', 1),
  ('varilla_roscada', 'Arandelas', 'arandela', 1),
  ('varilla_roscada', 'Antigripante', 'sellador_rosca', 1),
  ('varilla_roscada', 'Antigripante', 'lubricante', 2),
  ('baranda', 'Herrajes y conectores', 'herraje_arq', 1),
  ('baranda', 'Herrajes y conectores', 'arq_otro', 2),
  ('baranda', 'Accesorios para vidrio', 'acc_vidrio', 1),
  ('baranda', 'Adhesivo / sellador de montaje', 'adhesivo_montaje', 1),
  ('baranda', 'Abrasivos de acabado', 'flap', 1),
  ('baranda', 'Abrasivos de acabado', 'acabado', 2),
  ('baranda', 'Abrasivos de acabado', 'pulido', 3),
  ('baranda', 'Limpiador / pulidor', 'limpieza', 1),
  ('griferia', 'Accesorios y repuestos', 'acc_bano', 1),
  ('griferia', 'Accesorios y repuestos', 'herraje_arq', 2),
  ('griferia', 'Selladores / fijadores', 'adhesivo_montaje', 1),
  ('griferia', 'Selladores / fijadores', 'sellador_rosca', 2),
  ('griferia', 'Limpiador', 'limpieza', 1),
  ('tungsteno', 'Varilla TIG de aporte', 'varilla_tig', 1),
  ('tungsteno', 'Respaldo de raíz', 'respaldo', 1),
  ('tungsteno', 'Química de terminación', 'decapante', 1),
  ('tungsteno', 'Química de terminación', 'pasivante', 2),
  ('tungsteno', 'Química de terminación', 'neutralizante', 3),
  ('tungsteno', 'Acabado', 'flap', 1),
  ('tungsteno', 'Acabado', 'acabado', 2),
  ('tungsteno', 'Acabado', 'lija', 3),
  ('varilla_tig', 'Electrodo de tungsteno', 'tungsteno', 1),
  ('varilla_tig', 'Respaldo de raíz', 'respaldo', 1),
  ('varilla_tig', 'Química de terminación', 'decapante', 1),
  ('varilla_tig', 'Química de terminación', 'pasivante', 2),
  ('varilla_tig', 'Química de terminación', 'neutralizante', 3),
  ('varilla_tig', 'Abrasivos', 'flap', 1),
  ('varilla_tig', 'Abrasivos', 'acabado', 2),
  ('alambre_mig', 'Antiproyecciones', 'antiproyecciones', 1),
  ('alambre_mig', 'Química de terminación', 'decapante', 1),
  ('alambre_mig', 'Química de terminación', 'pasivante', 2),
  ('alambre_mig', 'Química de terminación', 'neutralizante', 3),
  ('alambre_mig', 'Abrasivos', 'disco_corte', 1),
  ('alambre_mig', 'Abrasivos', 'flap', 2),
  ('alambre_mig', 'Abrasivos', 'lija', 3),
  ('electrodo_revestido', 'Antiproyecciones', 'antiproyecciones', 1),
  ('electrodo_revestido', 'Abrasivos', 'disco_corte', 1),
  ('electrodo_revestido', 'Abrasivos', 'flap', 2),
  ('electrodo_revestido', 'Abrasivos', 'lija', 3),
  ('electrodo_revestido', 'Química de terminación', 'decapante', 1),
  ('electrodo_revestido', 'Química de terminación', 'pasivante', 2),
  ('electrodo_revestido', 'Química de terminación', 'neutralizante', 3),
  ('disco_corte', 'Acabado progresivo', 'flap', 1),
  ('disco_corte', 'Acabado progresivo', 'lija', 2),
  ('disco_corte', 'Acabado progresivo', 'acabado', 3),
  ('disco_corte', 'Cepillo de inox', 'cepillo', 1),
  ('disco_corte', 'Decapado y pasivado', 'decapante', 1),
  ('disco_corte', 'Decapado y pasivado', 'pasivante', 2),
  ('decapante', 'Secuencia: pasivar y neutralizar', 'pasivante', 1),
  ('decapante', 'Secuencia: pasivar y neutralizar', 'neutralizante', 2),
  ('decapante', 'Limpiadores y protección', 'limpieza', 1),
  ('decapante', 'Limpiadores y protección', 'revestimiento', 2),
  ('decapante', 'Verificación', 'detector', 1),
  ('decapante', 'Verificación', 'ndt', 2)
) as v(tipo, complemento, categoria, orden)
join tipo_producto tp on tp.codigo = v.tipo
join complemento c on c.tipo_producto_id = tp.id and c.nombre = v.complemento
join categoria cat on cat.codigo = v.categoria
on conflict do nothing;

-- Aporte de soldadura por familia de grado.
insert into aporte_por_grado (grado, aporte, motivo) values
  ('304', '308L', '308L sobre-aleado: compensa la dilución; aporte estándar de austeníticos 18/8.'),
  ('310', '310', 'Aporte 310 (25/20) para mantener el alto Cr/Ni y la resistencia en caliente.'),
  ('316', '316L', 'Aporte 316L para conservar el molibdeno y la resistencia al picado por cloruros.')
on conflict (grado) do nothing;

-- La columna Calidad del catalogo trae 304L / 316L / 310S, no 304 / 316 / 310.
-- Sin este colapso el aporte no matchea justo en el caso mas comun.
insert into grado_equivalencia (grado, familia) values
  ('304', '304'),
  ('304L', '304'),
  ('304H', '304'),
  ('316', '316'),
  ('316L', '316'),
  ('316TI', '316'),
  ('310', '310'),
  ('310S', '310')
on conflict (grado) do nothing;

-- 14 notas tecnicas por linea de producto.
insert into nota_tecnica (ambito, ambito_id, texto, orden)
select 'dominio', d.id, v.texto, v.orden
from (values
  ('tuberia', 'Hacer coincidir el grado de caño, accesorio y aporte; mezclar grados causa corrosión y pérdida de propiedades.', 1),
  ('tuberia', 'Toda soldadura debe decaparse y pasivarse: la coloración de revenido es zona empobrecida en cromo.', 2),
  ('sanitario', 'En contacto con producto, aporte 316L bajo carbono y back-purge para no oxidar la raíz interior.', 1),
  ('sanitario', 'La junta es el punto de desgaste: confirmar material según fluido, temperatura y CIP.', 2),
  ('materiaprima', 'Abrasivos y cepillos de uso exclusivo en inox; si tocaron acero al carbono generan óxido.', 1),
  ('materiaprima', 'Tras cortar o amolar, decapar y pasivar la zona trabajada.', 2),
  ('bulones', 'El galling es el problema nº1 del inox: ofrecer siempre antigripante con bulonería y espárragos.', 1),
  ('bulones', 'Verificar que tuerca y arandela sean del mismo grado que el bulón.', 2),
  ('arquitectura', 'Las uniones de pasamanos van con adhesivo de montaje; ofrecer limpiador/pulidor para mantenimiento.', 1),
  ('tapas', 'La junta de la tapa es consumible: venta recurrente de repuesto.', 1),
  ('soldadura', 'No mezclar abrasivos usados en acero al carbono. Proteger la raíz en cañería.', 1),
  ('abrasivos', 'Respetar la secuencia de grano (corte→flap grueso→flap fino→vellón).', 1),
  ('quimica', 'Seguridad: decapante y pasivante contienen ácidos (HF/HNO₃). Usar EPP y neutralizar residuos.', 1),
  ('quimica', 'El pasivado no reemplaza al decapado: primero quitar el óxido, después pasivar.', 2)
) as v(dominio, texto, orden)
join dominio d on d.codigo = v.dominio
where not exists (
  select 1 from nota_tecnica nt
  where nt.ambito = 'dominio' and nt.ambito_id = d.id and nt.texto = v.texto
);

-- 8 procesos (puerta B, pantalla en F2).
--
-- grado_tipico es BORRADOR: entra con revisado = false y motivo_grado vacio. La
-- justificacion tecnica del grado la escribe Oficina Tecnica; no se genera desde aca.
insert into proceso (codigo, nombre, grado_tipico, motivo_grado, revisado, orden) values
  ('cerveceria', 'Cerveceria', '304L / 316L en contacto', '', false, 1),
  ('lacteos', 'Lacteos y alimentos', '304L / 316L', '', false, 2),
  ('farma', 'Farma', '316L', '', false, 3),
  ('vinos', 'Vinos y tanques', '304L / 316L', '', false, 4),
  ('quimica', 'Quimica e industrial', '304L / 316L / 310 con temperatura', '', false, 5),
  ('oil_gas', 'O&G y alta presion', '316L', '', false, 6),
  ('arquitectura', 'Arquitectura', '304 interior / 316 exterior y costa', '', false, 7),
  ('estructural', 'Estructural y taller', '304 / 430 segun exposicion', '', false, 8)
on conflict (codigo) do nothing;

-- Familias tipicas de cada proceso. Todas entran como 'reco': el blueprint lista las
-- familias pero no su prioridad, y asignarla es parte de la revision de Oficina Tecnica.
insert into proceso_categoria (proceso_id, categoria_id, prioridad, orden)
select p.id, cat.id, 'reco'::prioridad_complemento, v.orden
from (values
  ('cerveceria', 'acc_valvula_san', 1),
  ('cerveceria', 'union_sanitaria', 2),
  ('cerveceria', 'valvula_san', 3),
  ('cerveceria', 'bomba', 4),
  ('cerveceria', 'acc_soldar_san', 5),
  ('lacteos', 'acc_soldar_san', 1),
  ('lacteos', 'union_sanitaria', 2),
  ('lacteos', 'bomba', 3),
  ('lacteos', 'tapa_puerta', 4),
  ('lacteos', 'valvula_san', 5),
  ('farma', 'acc_soldar_san', 1),
  ('farma', 'tubo', 2),
  ('farma', 'junta', 3),
  ('farma', 'union_sanitaria', 4),
  ('vinos', 'tapa_puerta', 1),
  ('vinos', 'acc_tanque', 2),
  ('vinos', 'sistema_limpieza', 3),
  ('vinos', 'junta', 4),
  ('vinos', 'valvula_san', 5),
  ('quimica', 'cano', 1),
  ('quimica', 'acc_soldar_ind', 2),
  ('quimica', 'brida', 3),
  ('quimica', 'valvula_ind', 4),
  ('quimica', 'junta', 5),
  ('oil_gas', 'instrumentacion', 1),
  ('oil_gas', 'acc_rosc_sw', 2),
  ('oil_gas', 'valvula_ind', 3),
  ('oil_gas', 'niple', 4),
  ('arquitectura', 'baranda', 1),
  ('arquitectura', 'griferia', 2),
  ('arquitectura', 'herraje_arq', 3),
  ('arquitectura', 'acc_vidrio', 4),
  ('arquitectura', 'acc_bano', 5),
  ('estructural', 'chapa', 1),
  ('estructural', 'barra', 2),
  ('estructural', 'planchuela', 3),
  ('estructural', 'angulo', 4),
  ('estructural', 'cano', 5)
) as v(proceso, categoria, orden)
join proceso p on p.codigo = v.proceso
join categoria cat on cat.codigo = v.categoria
on conflict (proceso_id, categoria_id) do nothing;

-- Una fila de link por categoria activa, vacia. Es lo que alimenta el reporte de
-- cobertura: sin filas, el panel no tendria que mostrar y no se sabria que falta cargar.
insert into link_categoria (categoria_id)
select id from categoria where activo
on conflict (categoria_id) do nothing;

commit;
